global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker-sec-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8081"]
  
  - job_name: "docker-sec-cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]