services:
  backend:
    container_name: docker-sel-backend
    image: iezekiil/docker-sec-backend:1a9eb03
    ports:
      - 8081:8081
    networks:
      - app

  frontend:
    container_name: docker-sel-frontend
    image: iezekiil/docker-sec-frontend:1a9eb03
    environment:
      - VUE_APP_API_URL=http://backend:8081
    ports:
      - 80:80
    networks:
      - app

networks:
  app:
